language: python
python:
  - "3.5"
cache: pip
services:
  - postgresql
install:
  - pip install -r ./api/requirements.txt
  - pip install codecov
script:
  - python ./api/manage.py migrate
  - coverage run --source="./api/." --omit="*migrations*" ./api/manage.py test --testrunner "rooms.custom_test_runner.NoDbTestRunner"
after_success:
  - codecov
